FROM node:20-alpine AS base
RUN corepack enable && corepack prepare pnpm@9.15.0 --activate

FROM base AS builder
WORKDIR /app

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml* .npmrc ./
COPY packages/shared-domain/package.json ./packages/shared-domain/
COPY packages/shared-config/package.json ./packages/shared-config/
COPY packages/shared-ui/package.json ./packages/shared-ui/
COPY packages/shared-test/package.json ./packages/shared-test/
COPY services/ecd/package.json ./services/ecd/
COPY services/planning/package.json ./services/planning/
COPY services/facturatie/package.json ./services/facturatie/
COPY services/workflow-bridge/package.json ./services/workflow-bridge/
COPY apps/web/package.json ./apps/web/
COPY adapters/ons-import/package.json ./adapters/ons-import/

RUN echo "node-linker=hoisted" >> .npmrc && \
    (pnpm install --frozen-lockfile || pnpm install)

COPY tsconfig.base.json ./
COPY packages/shared-domain/ ./packages/shared-domain/
COPY packages/shared-config/ ./packages/shared-config/
COPY packages/shared-ui/ ./packages/shared-ui/
COPY apps/web/ ./apps/web/

ENV STANDALONE=true
RUN pnpm --filter @openzorg/shared-domain build && \
    pnpm --filter @openzorg/shared-config build && \
    cd apps/web && ../../node_modules/.bin/next build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static
USER nextjs
EXPOSE 3000
ENV PORT=3000
CMD ["node", "apps/web/server.js"]
